import type { CourseResource } from "./types";

/**
 * Curated public learning resources.
 * Content is original summaries; links point to public GitHub/docs/articles only.
 * We do not mirror WeChat paywalled posts — prefer open mirrors or official docs.
 */
export const courseResources: CourseResource[] = [
  {
    id: "langgraph-101-ts",
    title: "langchain-ai/langgraph-101-ts",
    url: "https://github.com/langchain-ai/langgraph-101-ts",
    kind: "github",
    track: "状态编排",
    tags: ["LangGraph", "HITL", "Supervisor", "TypeScript"],
    language: "en",
    summary: "官方 TypeScript Workshop：从基础 Agent 到 Supervisor、验证与记忆。",
    why: "与本站技术栈一致，适合对照第 8–12 章做 Studio 可视化调试。",
  },
  {
    id: "agents-from-scratch-ts",
    title: "langchain-ai/agents-from-scratch-ts",
    url: "https://github.com/langchain-ai/agents-from-scratch-ts",
    kind: "github",
    track: "状态编排",
    tags: ["HITL", "Memory", "Email Agent"],
    language: "en",
    summary: "邮件助手递进实验：基础 Agent → Human-in-the-loop → 持久记忆。",
    why: "HITL 与长期记忆的最小可运行路径，可直接改成 TypeScript 服务。",
  },
  {
    id: "agent-ai-typescript",
    title: "tostechbr/agent-ai-typescript",
    url: "https://github.com/tostechbr/agent-ai-typescript",
    kind: "github",
    track: "认知基础",
    tags: ["Learning Path", "Modules", "Checklist"],
    language: "en",
    summary: "按模块拆分的 TS Agent 学习清单：基础、工具、图、RAG、生产。",
    why: "适合对照本站章节做“完成勾选”，发现自己缺哪一块。",
  },
  {
    id: "agentic-roadmap",
    title: "Agentic AI Roadmap with Notes and Projects",
    url: "https://github.com/AdilShamim8/Agentic-AI-Roadmap-with-Notes-and-Projects",
    kind: "github",
    track: "实战进阶",
    tags: ["Roadmap", "MCP", "A2A", "Production"],
    language: "en",
    summary: "覆盖 MCP、A2A、多 Agent 与生产部署的长周期路线图（偏 Python）。",
    why: "用它补本站选修深度；概念迁移到 Node.js/TS 即可。",
  },
  {
    id: "agent-learning-zh",
    title: "Haozhe-Xing/agent_learning",
    url: "https://github.com/haozhe-xing/agent_learning",
    kind: "github",
    track: "认知基础",
    tags: ["中文", "RAG", "MCP", "Multi-Agent"],
    language: "zh",
    summary: "系统化中文 Agent 教程，含初学者/工程/研究/项目四条路径。",
    why: "中文体系完整，适合和本站章节交叉阅读，尤其是协议与评估部分。",
  },
  {
    id: "awesome-ai-learning",
    title: "Ming-H/awesome-ai-learning",
    url: "https://github.com/Ming-H/awesome-ai-learning",
    kind: "github",
    track: "实战进阶",
    tags: ["Awesome", "MCP", "RAG", "Skills"],
    language: "zh",
    summary: "高质量资源导航：Prompt、RAG、Agent、MCP、Skills、推理部署。",
    why: "当目录用：每周只深挖 1–2 个链接，避免收藏式学习。",
  },
  {
    id: "build-your-own-ai-agent",
    title: "Lay4U/build-your-own-ai-agent",
    url: "https://github.com/Lay4U/build-your-own-ai-agent",
    kind: "github",
    track: "工具与协议",
    tags: ["From Scratch", "MCP", "No Framework"],
    language: "en",
    summary: "12 个去框架项目：手写 Tool Loop、RAG、MCP、多 Agent。",
    why: "理解黑盒前先手写一轮循环；再回到 LangChain/LangGraph 会更清醒。",
  },
  {
    id: "awesome-agentic-engineering",
    title: "awesome-agentic-engineering-resources",
    url: "https://github.com/EthicalML/awesome-agentic-engineering-resources",
    kind: "github",
    track: "工程上线",
    tags: ["Security", "Eval", "Observability", "UX"],
    language: "en",
    summary: "Agentic Engineering 主题地图：编码助手、RAG、MCP、评估、护栏。",
    why: "用来对照本站“工程上线”轨道，查漏补缺比追热点更有效。",
  },
  {
    id: "hi-agent",
    title: "joker-yjc/hi-agent",
    url: "https://github.com/joker-yjc/hi-agent",
    kind: "github",
    track: "模型与提示",
    tags: ["前端", "TypeScript", "MCP", "RAG"],
    language: "zh",
    summary: "面向前端的渐进式 AI 应用学习：API → Chat UI → RAG → Agent → MCP。",
    why: "路径与本站高度重合，可作第二套动手仓库。",
  },
  {
    id: "book-langchain-agent",
    title: "diguike/book-langchain-agent",
    url: "https://github.com/diguike/book-langchain-agent",
    kind: "github",
    track: "模型与提示",
    tags: ["LangChain.js", "中文", "RAG", "Observability"],
    language: "zh",
    summary: "LangChain.js 1.x 系统化中文教程：LCEL、LangGraph、RAG、评估与项目。",
    why: "API 细节比博客更全；读完后应能独立查官方文档。",
  },
  {
    id: "langchain-js-docs",
    title: "LangChain.js Documentation",
    url: "https://js.langchain.com/",
    kind: "docs",
    track: "模型与提示",
    tags: ["Official", "API"],
    language: "en",
    summary: "LangChain JavaScript/TypeScript 官方文档。",
    why: "任何第三方教程冲突时，以官方 API 为准。",
  },
  {
    id: "langgraph-js-docs",
    title: "LangGraph.js Documentation",
    url: "https://langchain-ai.github.io/langgraphjs/",
    kind: "docs",
    track: "状态编排",
    tags: ["Official", "StateGraph", "Checkpoint"],
    language: "en",
    summary: "LangGraph.js 官方概念、How-to 与 API。",
    why: "状态、interrupt、checkpoint 必须以官方语义理解。",
  },
  {
    id: "mcp-langchain-js",
    title: "LangChain MCP Adapters (JS)",
    url: "https://docs.langchain.com/oss/javascript/langchain/mcp",
    kind: "docs",
    track: "工具与协议",
    tags: ["MCP", "Adapters", "Official"],
    language: "en",
    summary: "用 @langchain/mcp-adapters 把 MCP Server 工具接入 Agent。",
    why: "本站 MCP 章的权威参考与版本锚点。",
  },
  {
    id: "mcp-spec",
    title: "Model Context Protocol Specification",
    url: "https://modelcontextprotocol.io/",
    kind: "docs",
    track: "工具与协议",
    tags: ["MCP", "Protocol"],
    language: "en",
    summary: "MCP 官方站点：工具、资源、提示与传输层约定。",
    why: "写 MCP Server 前先读协议边界，避免把业务权限塞进模型侧。",
  },
  {
    id: "langsmith-trajectory-evals",
    title: "Trajectory Evaluations",
    url: "https://docs.langchain.com/langsmith/trajectory-evals",
    kind: "docs",
    track: "工程上线",
    tags: ["Eval", "LangSmith", "Trajectory"],
    language: "en",
    summary: "用轨迹匹配或 LLM Judge 评估 Agent 工具路径。",
    why: "只评最终答案不够；轨迹评估是生产回归的关键能力。",
  },
  {
    id: "langchain-academy",
    title: "LangChain Academy",
    url: "https://academy.langchain.com/",
    kind: "course",
    track: "状态编排",
    tags: ["Course", "LangGraph", "Multi-Agent"],
    language: "en",
    summary: "官方免费课程：Intro to LangGraph、Multi-Agent Systems 等。",
    why: "视频补直觉，练习请用 TypeScript 重写并加入评估集。",
  },
  {
    id: "deeplearning-ai-agents-langgraph",
    title: "AI Agents in LangGraph (DeepLearning.AI)",
    url: "https://www.deeplearning.ai/short-courses/ai-agents-in-langgraph/",
    kind: "course",
    track: "状态编排",
    tags: ["Course", "Short"],
    language: "en",
    summary: "短课形式的 LangGraph Agent 实践。",
    why: "适合周末冲刺；结束后立刻在本站实验里复现。",
  },
  {
    id: "frontend-agent-path-article",
    title: "前端开发者的 AI Agent 全栈学习路线",
    url: "https://jishuzhan.net/article/2050451524652957698",
    kind: "article",
    track: "认知基础",
    tags: ["中文", "前端", "学习路线"],
    language: "zh",
    summary: "公开中文文章：Prompt、RAG、多 Agent 与工程化落地的阶段划分。",
    why: "对照本站轨道，检查自己是否跳过了 Prompt/RAG 质量环节。",
  },
  {
    id: "langchainjs-frontend-guide",
    title: "LangChain.js + LangGraph.js 前端 AI 开发实战指南",
    url: "https://jishuzhan.net/article/2045058781571252225",
    kind: "article",
    track: "模型与提示",
    tags: ["中文", "LangChain.js", "前端"],
    language: "zh",
    summary: "面向前端的栈说明与分阶段学习清单。",
    why: "可作为“为什么选 Node.js”的补充论据，细节仍以官方文档为准。",
  },
  {
    id: "juejin-agent-course-overview",
    title: "AI Agent 开发从 0 到 1（掘金公开文）",
    url: "https://juejin.cn/post/7519131837362438179",
    kind: "article",
    track: "认知基础",
    tags: ["中文", "Prompt", "RAG"],
    language: "zh",
    summary: "公开综述：Prompt、RAG 与 Agent 框架的入门叙事。",
    why: "适合给团队做共识阅读；落地实现请回到本站代码实验。",
  },
  {
    id: "vercel-deployments-docs",
    title: "Vercel Deployments",
    url: "https://vercel.com/docs/deployments",
    kind: "docs",
    track: "工程上线",
    tags: ["Vercel", "Deployment", "Status", "Official"],
    language: "en",
    summary: "Vercel 官方 Deployment 概念、状态与生命周期说明。",
    why: "控制台状态或发布流程发生变化时，用它校准 P03 的对象与状态语义。",
  },
  {
    id: "vercel-environments-docs",
    title: "Vercel Environments",
    url: "https://vercel.com/docs/deployments/environments",
    kind: "docs",
    track: "工程上线",
    tags: ["Vercel", "Production", "Preview", "Development"],
    language: "en",
    summary: "Production、Preview 与 Development 环境的官方定义和行为。",
    why: "用于确认环境作用域，避免只凭控制台标签判断数据和权限边界。",
  },
  {
    id: "vercel-environment-variables-docs",
    title: "Vercel Environment Variables",
    url: "https://vercel.com/docs/environment-variables",
    kind: "docs",
    track: "工程上线",
    tags: ["Vercel", "Environment Variables", "Secrets", "Official"],
    language: "en",
    summary: "Vercel 环境变量作用域、敏感值与部署生效规则。",
    why: "变量配置属于安全边界；课程不复制密钥值，规则以官方文档为准。",
  },
  {
    id: "vercel-builds-docs",
    title: "Vercel Builds",
    url: "https://vercel.com/docs/deployments/builds",
    kind: "docs",
    track: "工程上线",
    tags: ["Vercel", "Build Logs", "Cache", "Official"],
    language: "en",
    summary: "Vercel 构建阶段、缓存、构建命令与日志说明。",
    why: "用于区分构建失败和运行时失败，并核对当前构建行为。",
  },
  {
    id: "vercel-managing-deployments-docs",
    title: "Vercel Managing Deployments",
    url: "https://vercel.com/docs/deployments/managing-deployments",
    kind: "docs",
    track: "工程上线",
    tags: ["Vercel", "Redeploy", "Promote", "Rollback"],
    language: "en",
    summary: "Vercel 重新部署、提升与回滚操作的官方说明。",
    why: "这些操作会改变生产流量；执行前必须核对最新语义、限制和恢复方式。",
  },
  {
    id: "vercel-logs-docs",
    title: "Vercel Logs",
    url: "https://vercel.com/docs/logs",
    kind: "docs",
    track: "工程上线",
    tags: ["Vercel", "Runtime Logs", "Build Logs", "Debugging"],
    language: "en",
    summary: "Vercel 构建日志、运行时日志和相关筛选能力。",
    why: "用于按环境、版本和时间定位请求，同时确认日志保留与检索能力。",
  },
  {
    id: "vercel-observability-docs",
    title: "Vercel Observability",
    url: "https://vercel.com/docs/observability",
    kind: "docs",
    track: "工程上线",
    tags: ["Vercel", "Observability", "Analytics", "Performance"],
    language: "en",
    summary: "Vercel 请求、函数、流量和性能观测能力总览。",
    why: "用于理解平台趋势信号，并与 Sentry、Supabase、Inngest 的事实边界分开。",
  },
  {
    id: "vercel-usage-docs",
    title: "Vercel Limits and Usage",
    url: "https://vercel.com/docs/limits",
    kind: "docs",
    track: "工程上线",
    tags: ["Vercel", "Usage", "Limits", "Cost"],
    language: "en",
    summary: "Vercel 当前资源限制与用量说明。",
    why: "套餐数字会变化；巡检只讲趋势和异常，用量边界以当前官方文档为准。",
  },
  {
    id: "supabase-database-docs",
    title: "Supabase Database Overview",
    url: "https://supabase.com/docs/guides/database/overview",
    kind: "docs",
    track: "工程上线",
    tags: ["Supabase", "Postgres", "Database", "Official"],
    language: "en",
    summary: "Supabase 托管 Postgres、连接与数据库能力总览。",
    why: "用于建立 Project 与 Postgres 的职责边界，平台行为变化时以官方说明为准。",
  },
  {
    id: "supabase-tables-docs",
    title: "Supabase Tables and Data",
    url: "https://supabase.com/docs/guides/database/tables",
    kind: "docs",
    track: "工程上线",
    tags: ["Supabase", "Schema", "Table", "Data"],
    language: "en",
    summary: "Supabase Schema、Table、列与数据入口说明。",
    why: "用于理解 Table Editor；生产结构变更仍应回到版本化迁移。",
  },
  {
    id: "supabase-migrations-docs",
    title: "Supabase Database Migrations",
    url: "https://supabase.com/docs/guides/deployment/database-migrations",
    kind: "docs",
    track: "工程上线",
    tags: ["Supabase", "Migration", "CLI", "Deployment"],
    language: "en",
    summary: "使用 Supabase CLI 与仓库管理数据库迁移。",
    why: "迁移文件是生产结构变更的事实来源，避免控制台修改形成漂移。",
  },
  {
    id: "supabase-database-health-docs",
    title: "Supabase Database Size and Health",
    url: "https://supabase.com/docs/guides/platform/database-size",
    kind: "docs",
    track: "工程上线",
    tags: ["Supabase", "Database Size", "Health", "Usage"],
    language: "en",
    summary: "Supabase 数据库容量与相关健康信号说明。",
    why: "用于按趋势判断容量和资源压力，不把单个面板数字当作根因。",
  },
  {
    id: "supabase-auth-docs",
    title: "Supabase Auth",
    url: "https://supabase.com/docs/guides/auth",
    kind: "docs",
    track: "工程上线",
    tags: ["Supabase", "Auth", "Provider", "Session"],
    language: "en",
    summary: "Supabase 身份、Provider、用户与 Session 能力总览。",
    why: "用于区分身份验证和数据授权，避免把登录成功误当成权限正确。",
  },
  {
    id: "supabase-redirect-urls-docs",
    title: "Supabase Redirect URLs",
    url: "https://supabase.com/docs/guides/auth/redirect-urls",
    kind: "docs",
    track: "工程上线",
    tags: ["Supabase", "Redirect URL", "OAuth", "Preview"],
    language: "en",
    summary: "Supabase Site URL、Redirect URL 与移动链接说明。",
    why: "Preview 与 Production 回调经常不同，登录异常时应先核对当前官方匹配规则。",
  },
  {
    id: "supabase-rls-docs",
    title: "Supabase Row Level Security",
    url: "https://supabase.com/docs/guides/database/postgres/row-level-security",
    kind: "docs",
    track: "工程上线",
    tags: ["Supabase", "RLS", "Policy", "Authorization"],
    language: "en",
    summary: "Postgres RLS、Policy、角色与 auth.uid() 的官方说明。",
    why: "RLS 是浏览器访问数据的关键边界；策略语义必须以官方与 Postgres 行为为准。",
  },
  {
    id: "supabase-logs-docs",
    title: "Supabase Logs",
    url: "https://supabase.com/docs/guides/platform/logs",
    kind: "docs",
    track: "工程上线",
    tags: ["Supabase", "Logs", "Auth", "Postgres"],
    language: "en",
    summary: "Supabase 平台日志、来源与检索能力。",
    why: "用于围绕窄时间窗定位 Auth、API 与数据库异常，同时遵守日志隐私边界。",
  },
  {
    id: "supabase-backups-docs",
    title: "Supabase Backups",
    url: "https://supabase.com/docs/guides/platform/backups",
    kind: "docs",
    track: "工程上线",
    tags: ["Supabase", "Backups", "PITR", "Recovery"],
    language: "en",
    summary: "Supabase 备份、时间点恢复与恢复方式说明。",
    why: "套餐和能力会变化；恢复前需核对当前可用性，并在隔离项目完成演练。",
  },
  {
    id: "supabase-api-keys-docs",
    title: "Supabase API Keys",
    url: "https://supabase.com/docs/guides/api/api-keys",
    kind: "docs",
    track: "工程上线",
    tags: ["Supabase", "API Keys", "Publishable", "Secret"],
    language: "en",
    summary: "Supabase Publishable、Secret 与历史 anon / service_role 密钥边界。",
    why: "密钥产品正在演进；客户端与服务端权限边界必须跟随官方当前说明。",
  },
  {
    id: "inngest-concepts-docs",
    title: "Inngest Learn",
    url: "https://www.inngest.com/docs/learn",
    kind: "docs",
    track: "工程上线",
    tags: ["Inngest", "Event-driven", "Functions", "Official"],
    language: "en",
    summary: "Inngest 事件驱动、Function 与运行模型总览。",
    why: "建立后台任务心智模型，避免把 Event、Function 与 Run 混成一个对象。",
  },
  {
    id: "inngest-events-docs",
    title: "Inngest Events",
    url: "https://www.inngest.com/docs/events",
    kind: "docs",
    track: "工程上线",
    tags: ["Inngest", "Event", "Payload", "Trigger"],
    language: "en",
    summary: "Inngest Event 的发送、触发与数据边界。",
    why: "用于判断事件是否被接收和触发，不把消息成功误判成业务完成。",
  },
  {
    id: "inngest-functions-docs",
    title: "Inngest Functions",
    url: "https://www.inngest.com/docs/functions",
    kind: "docs",
    track: "工程上线",
    tags: ["Inngest", "Function", "Step", "Retries"],
    language: "en",
    summary: "Inngest Function、Step、触发和执行定义说明。",
    why: "用于核对后台函数配置、步骤边界和代码部署是否同步。",
  },
  {
    id: "inngest-runs-docs",
    title: "Inngest Runs",
    url: "https://www.inngest.com/docs/runs",
    kind: "docs",
    track: "工程上线",
    tags: ["Inngest", "Run", "Status", "Debugging"],
    language: "en",
    summary: "Inngest Run 状态、时间线与排障入口。",
    why: "用状态和时间串联一次后台执行，不复制 payload 或运行标识。",
  },
  {
    id: "inngest-retries-docs",
    title: "Inngest Retries",
    url: "https://www.inngest.com/docs/features/retries",
    kind: "docs",
    track: "工程上线",
    tags: ["Inngest", "Retry", "Backoff", "Failure"],
    language: "en",
    summary: "Inngest 重试、退避与失败分类说明。",
    why: "把可恢复错误与确定性错误分开，避免重试风暴和重复副作用。",
  },
  {
    id: "inngest-concurrency-docs",
    title: "Inngest Concurrency",
    url: "https://www.inngest.com/docs/guides/concurrency",
    kind: "docs",
    track: "工程上线",
    tags: ["Inngest", "Concurrency", "Throttle", "Rate Limit"],
    language: "en",
    summary: "Inngest 并发、限流和队列控制。",
    why: "用并发上限保护下游和成本，避免把积压误判成增加并发就能解决。",
  },
  {
    id: "inngest-idempotency-docs",
    title: "Inngest Idempotency",
    url: "https://www.inngest.com/docs/guides/idempotency",
    kind: "docs",
    track: "工程上线",
    tags: ["Inngest", "Idempotency", "Side Effects", "Reliability"],
    language: "en",
    summary: "Inngest 幂等键与重复执行安全边界。",
    why: "Replay、Rerun 和 Retry 前先设计幂等，避免重复通知、写入或扣费。",
  },
  {
    id: "inngest-usage-docs",
    title: "Inngest Usage",
    url: "https://www.inngest.com/docs/platform/usage",
    kind: "docs",
    track: "工程上线",
    tags: ["Inngest", "Usage", "Cost", "Executions"],
    language: "en",
    summary: "Inngest 当前执行量与用量维度说明。",
    why: "用量和套餐会变化；课程只建立趋势巡检，不写死额度数字。",
  },
];

export function getResource(id: string): CourseResource | undefined {
  return courseResources.find((resource) => resource.id === id);
}

export function resourcesByTrack(track: CourseResource["track"]): CourseResource[] {
  return courseResources.filter((resource) => resource.track === track);
}

export function searchResources(query: string): CourseResource[] {
  const normalized = query.trim().toLocaleLowerCase("zh-CN");
  if (!normalized) return courseResources;
  return courseResources.filter((resource) =>
    [resource.title, resource.summary, resource.why, ...resource.tags]
      .join(" ")
      .toLocaleLowerCase("zh-CN")
      .includes(normalized),
  );
}
