import type { CourseResource } from "./types";

/**
 * Curated public learning resources.
 * Content is original summaries; links point to public GitHub/docs/articles only.
 * We do not mirror WeChat paywalled posts — prefer open mirrors or official docs.
 */
export const courseResources: CourseResource[] = [
  {
    id: "langgraph-101-ts",
    title: "langchain-ai/langgraph-101-ts",
    url: "https://github.com/langchain-ai/langgraph-101-ts",
    kind: "github",
    track: "状态编排",
    tags: ["LangGraph", "HITL", "Supervisor", "TypeScript"],
    language: "en",
    summary: "官方 TypeScript Workshop：从基础 Agent 到 Supervisor、验证与记忆。",
    why: "与本站技术栈一致，适合对照第 8–12 章做 Studio 可视化调试。",
  },
  {
    id: "agents-from-scratch-ts",
    title: "langchain-ai/agents-from-scratch-ts",
    url: "https://github.com/langchain-ai/agents-from-scratch-ts",
    kind: "github",
    track: "状态编排",
    tags: ["HITL", "Memory", "Email Agent"],
    language: "en",
    summary: "邮件助手递进实验：基础 Agent → Human-in-the-loop → 持久记忆。",
    why: "HITL 与长期记忆的最小可运行路径，可直接改成 TypeScript 服务。",
  },
  {
    id: "agent-ai-typescript",
    title: "tostechbr/agent-ai-typescript",
    url: "https://github.com/tostechbr/agent-ai-typescript",
    kind: "github",
    track: "认知基础",
    tags: ["Learning Path", "Modules", "Checklist"],
    language: "en",
    summary: "按模块拆分的 TS Agent 学习清单：基础、工具、图、RAG、生产。",
    why: "适合对照本站章节做“完成勾选”，发现自己缺哪一块。",
  },
  {
    id: "agentic-roadmap",
    title: "Agentic AI Roadmap with Notes and Projects",
    url: "https://github.com/AdilShamim8/Agentic-AI-Roadmap-with-Notes-and-Projects",
    kind: "github",
    track: "实战进阶",
    tags: ["Roadmap", "MCP", "A2A", "Production"],
    language: "en",
    summary: "覆盖 MCP、A2A、多 Agent 与生产部署的长周期路线图（偏 Python）。",
    why: "用它补本站选修深度；概念迁移到 Node.js/TS 即可。",
  },
  {
    id: "agent-learning-zh",
    title: "Haozhe-Xing/agent_learning",
    url: "https://github.com/haozhe-xing/agent_learning",
    kind: "github",
    track: "认知基础",
    tags: ["中文", "RAG", "MCP", "Multi-Agent"],
    language: "zh",
    summary: "系统化中文 Agent 教程，含初学者/工程/研究/项目四条路径。",
    why: "中文体系完整，适合和本站章节交叉阅读，尤其是协议与评估部分。",
  },
  {
    id: "awesome-ai-learning",
    title: "Ming-H/awesome-ai-learning",
    url: "https://github.com/Ming-H/awesome-ai-learning",
    kind: "github",
    track: "实战进阶",
    tags: ["Awesome", "MCP", "RAG", "Skills"],
    language: "zh",
    summary: "高质量资源导航：Prompt、RAG、Agent、MCP、Skills、推理部署。",
    why: "当目录用：每周只深挖 1–2 个链接，避免收藏式学习。",
  },
  {
    id: "build-your-own-ai-agent",
    title: "Lay4U/build-your-own-ai-agent",
    url: "https://github.com/Lay4U/build-your-own-ai-agent",
    kind: "github",
    track: "工具与协议",
    tags: ["From Scratch", "MCP", "No Framework"],
    language: "en",
    summary: "12 个去框架项目：手写 Tool Loop、RAG、MCP、多 Agent。",
    why: "理解黑盒前先手写一轮循环；再回到 LangChain/LangGraph 会更清醒。",
  },
  {
    id: "awesome-agentic-engineering",
    title: "awesome-agentic-engineering-resources",
    url: "https://github.com/EthicalML/awesome-agentic-engineering-resources",
    kind: "github",
    track: "工程上线",
    tags: ["Security", "Eval", "Observability", "UX"],
    language: "en",
    summary: "Agentic Engineering 主题地图：编码助手、RAG、MCP、评估、护栏。",
    why: "用来对照本站“工程上线”轨道，查漏补缺比追热点更有效。",
  },
  {
    id: "hi-agent",
    title: "joker-yjc/hi-agent",
    url: "https://github.com/joker-yjc/hi-agent",
    kind: "github",
    track: "模型与提示",
    tags: ["前端", "TypeScript", "MCP", "RAG"],
    language: "zh",
    summary: "面向前端的渐进式 AI 应用学习：API → Chat UI → RAG → Agent → MCP。",
    why: "路径与本站高度重合，可作第二套动手仓库。",
  },
  {
    id: "book-langchain-agent",
    title: "diguike/book-langchain-agent",
    url: "https://github.com/diguike/book-langchain-agent",
    kind: "github",
    track: "模型与提示",
    tags: ["LangChain.js", "中文", "RAG", "Observability"],
    language: "zh",
    summary: "LangChain.js 1.x 系统化中文教程：LCEL、LangGraph、RAG、评估与项目。",
    why: "API 细节比博客更全；读完后应能独立查官方文档。",
  },
  {
    id: "langchain-js-docs",
    title: "LangChain.js Documentation",
    url: "https://js.langchain.com/",
    kind: "docs",
    track: "模型与提示",
    tags: ["Official", "API"],
    language: "en",
    summary: "LangChain JavaScript/TypeScript 官方文档。",
    why: "任何第三方教程冲突时，以官方 API 为准。",
  },
  {
    id: "langgraph-js-docs",
    title: "LangGraph.js Documentation",
    url: "https://langchain-ai.github.io/langgraphjs/",
    kind: "docs",
    track: "状态编排",
    tags: ["Official", "StateGraph", "Checkpoint"],
    language: "en",
    summary: "LangGraph.js 官方概念、How-to 与 API。",
    why: "状态、interrupt、checkpoint 必须以官方语义理解。",
  },
  {
    id: "mcp-langchain-js",
    title: "LangChain MCP Adapters (JS)",
    url: "https://docs.langchain.com/oss/javascript/langchain/mcp",
    kind: "docs",
    track: "工具与协议",
    tags: ["MCP", "Adapters", "Official"],
    language: "en",
    summary: "用 @langchain/mcp-adapters 把 MCP Server 工具接入 Agent。",
    why: "本站 MCP 章的权威参考与版本锚点。",
  },
  {
    id: "mcp-spec",
    title: "Model Context Protocol Specification",
    url: "https://modelcontextprotocol.io/",
    kind: "docs",
    track: "工具与协议",
    tags: ["MCP", "Protocol"],
    language: "en",
    summary: "MCP 官方站点：工具、资源、提示与传输层约定。",
    why: "写 MCP Server 前先读协议边界，避免把业务权限塞进模型侧。",
  },
  {
    id: "langsmith-trajectory-evals",
    title: "Trajectory Evaluations",
    url: "https://docs.langchain.com/langsmith/trajectory-evals",
    kind: "docs",
    track: "工程上线",
    tags: ["Eval", "LangSmith", "Trajectory"],
    language: "en",
    summary: "用轨迹匹配或 LLM Judge 评估 Agent 工具路径。",
    why: "只评最终答案不够；轨迹评估是生产回归的关键能力。",
  },
  {
    id: "langchain-academy",
    title: "LangChain Academy",
    url: "https://academy.langchain.com/",
    kind: "course",
    track: "状态编排",
    tags: ["Course", "LangGraph", "Multi-Agent"],
    language: "en",
    summary: "官方免费课程：Intro to LangGraph、Multi-Agent Systems 等。",
    why: "视频补直觉，练习请用 TypeScript 重写并加入评估集。",
  },
  {
    id: "deeplearning-ai-agents-langgraph",
    title: "AI Agents in LangGraph (DeepLearning.AI)",
    url: "https://www.deeplearning.ai/short-courses/ai-agents-in-langgraph/",
    kind: "course",
    track: "状态编排",
    tags: ["Course", "Short"],
    language: "en",
    summary: "短课形式的 LangGraph Agent 实践。",
    why: "适合周末冲刺；结束后立刻在本站实验里复现。",
  },
  {
    id: "frontend-agent-path-article",
    title: "前端开发者的 AI Agent 全栈学习路线",
    url: "https://jishuzhan.net/article/2050451524652957698",
    kind: "article",
    track: "认知基础",
    tags: ["中文", "前端", "学习路线"],
    language: "zh",
    summary: "公开中文文章：Prompt、RAG、多 Agent 与工程化落地的阶段划分。",
    why: "对照本站轨道，检查自己是否跳过了 Prompt/RAG 质量环节。",
  },
  {
    id: "langchainjs-frontend-guide",
    title: "LangChain.js + LangGraph.js 前端 AI 开发实战指南",
    url: "https://jishuzhan.net/article/2045058781571252225",
    kind: "article",
    track: "模型与提示",
    tags: ["中文", "LangChain.js", "前端"],
    language: "zh",
    summary: "面向前端的栈说明与分阶段学习清单。",
    why: "可作为“为什么选 Node.js”的补充论据，细节仍以官方文档为准。",
  },
  {
    id: "juejin-agent-course-overview",
    title: "AI Agent 开发从 0 到 1（掘金公开文）",
    url: "https://juejin.cn/post/7519131837362438179",
    kind: "article",
    track: "认知基础",
    tags: ["中文", "Prompt", "RAG"],
    language: "zh",
    summary: "公开综述：Prompt、RAG 与 Agent 框架的入门叙事。",
    why: "适合给团队做共识阅读；落地实现请回到本站代码实验。",
  },
];

export function getResource(id: string): CourseResource | undefined {
  return courseResources.find((resource) => resource.id === id);
}

export function resourcesByTrack(track: CourseResource["track"]): CourseResource[] {
  return courseResources.filter((resource) => resource.track === track);
}

export function searchResources(query: string): CourseResource[] {
  const normalized = query.trim().toLocaleLowerCase("zh-CN");
  if (!normalized) return courseResources;
  return courseResources.filter((resource) =>
    [resource.title, resource.summary, resource.why, ...resource.tags]
      .join(" ")
      .toLocaleLowerCase("zh-CN")
      .includes(normalized),
  );
}
